In [32]:
from huggingface_hub import notebook_login
notebook_login()

In [33]:
from datasets import Dataset, DatasetDict, Image
from pathlib import Path
import os

In [44]:
image_folder_train = Path("data_crop_residue_only/train/image")
label_folder_train = Path("data_crop_residue_only/train/label")
image_paths_train = [str(file) for file in image_folder_train.iterdir() if file.is_file()]
label_paths_train = [str(file) for file in label_folder_train.iterdir() if file.is_file()]

In [45]:
from PIL import Image as pil_image
for file_path in label_paths_train:
    with pil_image.open(file_path) as pil_mask:
        mask = np.array(pil_mask)
        # print("Mask shape:", mask.shape)
        # print(mask)
        # np.savetxt("mask.csv", np_mask, delimiter=",", fmt="%d")
        # print("Unique values:", np.unique(mask))
        # mask = np.array(img)
        mask[mask == 255] = 1
        # Create a new PIL image and save
        mask_binary = pil_image.fromarray(mask)
        mask_binary.save(file_path)


In [47]:
# your images can of course have a different extension
# semantic segmentation maps are typically stored in the png format
# image_paths_train = ["path/to/image_1.jpg/jpg", "path/to/image_2.jpg/jpg", ..., "path/to/image_n.jpg/jpg"]
# label_paths_train = ["path/to/annotation_1.png", "path/to/annotation_2.png", ..., "path/to/annotation_n.png"]
print(sorted(label_paths_train))

['data_crop_residue_only/train/label/IMG_0629_res_part01.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part02.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part03.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part04.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part05.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part06.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part07.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part08.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part09.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part10.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part11.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part12.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part13.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part14.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part15.tif', 'data_crop_residue_only/train/label/IMG_0629_res_part16.tif', 'data_c

In [48]:
# same for validation
# image_paths_validation = [...]
# label_paths_validation = [...]

def create_dataset(image_paths, label_paths):
    dataset = Dataset.from_dict({"image": sorted(image_paths),
                                "label": sorted(label_paths)})
    dataset = dataset.cast_column("image", Image())
    dataset = dataset.cast_column("label", Image())

    return dataset

In [49]:
# step 1: create Dataset objects
dataset = create_dataset(image_paths_train, label_paths_train)
# splits = dataset.train_test_split(test_size=0.2, seed=42)
# train_dataset = splits["train"]
# validation_dataset = splits["test"] 

In [50]:



# step 2: create DatasetDict
dataset = DatasetDict({
    "train": dataset,
    # "validation": validation_dataset,
  }
)

In [51]:
# step 3: push to hub (assumes you have ran the huggingface-cli login command in a terminal/notebook)
dataset.push_to_hub("agaid_residue_only")

# optionally, you can push to a private repo on the hub
# dataset.push_to_hub("name of repo on the hub", private=True)

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Map:   0%|          | 0/688 [00:00<?, ? examples/s]

Creating parquet from Arrow format:   0%|          | 0/7 [00:00<?, ?ba/s]

CommitInfo(commit_url='https://huggingface.co/datasets/Sowmith1999/agaid_residue_only/commit/7c9de1ff42334832384e2d0fe881f24044a320f6', commit_message='Upload dataset', commit_description='', oid='7c9de1ff42334832384e2d0fe881f24044a320f6', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/Sowmith1999/agaid_residue_only', endpoint='https://huggingface.co', repo_type='dataset', repo_id='Sowmith1999/agaid_residue_only'), pr_revision=None, pr_num=None)

In [12]:
print("hello world")

hello world


In [54]:

example_mask_path = label_paths_train[0]
print(example_mask_path)
with PIL.Image.open(example_mask_path) as pil_new_mask:
    np_mask = np.array(pil_new_mask)
    print("Mask shape:", np_mask.shape)
    print(np_mask)
    np.savetxt("mask_new_1.csv", np_mask, delimiter=",", fmt="%d")
    print("Unique values:", np.unique(np_mask))
    # mask = np.array(img)
    # mask[mask == 255] = 1
    # # Create a new PIL image and save
    # mask_binary = PIL.Image.fromarray(mask)
    # mask_binary.save("./new_mask.tif")


data_crop_residue_only/train/label/IMG_0814_res_part16.tif
Mask shape: (512, 512)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Unique values: [0 1]
